apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: phoenix
  name: storage-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-backend
  template:
    metadata:
      labels:
        app: storage-backend
    spec:
      containers:
      - name: storage-backend
        image: localhost:5001/storage-backend:latest
        ports:
        - containerPort: 3002
 
---
apiVersion: v1
kind: Service
metadata:
  namespace: phoenix
  name: storage-backend
spec:
  ports:
    - port: 80
      targetPort: 3002
  selector:
    app: storage-backend