apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: phoenix
  name: phoenix-mobile
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phoenix-mobile
  template:
    metadata:
      labels:
        app: phoenix-mobile
    spec:
      containers:
      - name: phoenix-mobile
        image: localhost:5001/phoenix-mobile-1:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  namespace: phoenix
  name: phoenix-mobile
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: phoenix-mobile
      