apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: phoenix
  name: phoenix-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phoenix-backend
  template:
    metadata:
      labels:
        app: phoenix-backend
    spec:
      containers:
      - name: phoenix-backend
        image: localhost:5001/phoenix-backend:latest
        ports:
        - containerPort: 3001
        env:
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: phoenix-backend-secret
                key: DB_NAME
          - name: USER_NAME
            valueFrom:
              secretKeyRef:
                name: phoenix-backend-secret
                key: USER_NAME
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: phoenix-backend-secret
                key: DB_PASSWORD
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: phoenix-backend-secret
                key: DB_HOST
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: phoenix-backend-secret
                key: DB_PORT
          - name: DB_TYPE
            valueFrom:
              secretKeyRef:
                name: phoenix-backend-secret
                key: DB_TYPE
          - name: FILE_SERVICE_HOST
            valueFrom:
              secretKeyRef:
                name: phoenix-backend-secret
                key: FILE_SERVICE_HOST
          - name: FILE_SERVICE_STATIC_HOST
            valueFrom:
              secretKeyRef:
                name: phoenix-backend-secret
                key: FILE_SERVICE_STATIC_HOST
          - name: JWT_SCRECT
            valueFrom:
              secretKeyRef:
                name: phoenix-backend-secret
                key: JWT_SCRECT
          - name: GOOGLE_ENTERPRISE_ID
            valueFrom:
              secretKeyRef:
                name: phoenix-backend-secret
                key: GOOGLE_ENTERPRISE_ID
          - name: GOOGLE_MDM_EMAIL
            valueFrom:
              secretKeyRef:
                name: phoenix-backend-secret
                key: GOOGLE_MDM_EMAIL
          - name: GOOGLE_MDM_KEY_ID
            valueFrom:
              secretKeyRef:
                name: phoenix-backend-secret
                key: GOOGLE_MDM_KEY_ID

---
apiVersion: v1
kind: Service
metadata:
  namespace: phoenix
  name: phoenix-backend
spec:
  ports:
    - port: 80
      targetPort: 3001
  selector:
    app: phoenix-backend